# Generated by Django 4.0 on 2022-01-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_detail_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='polotician_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/Polititcian_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
