# Generated by Django 4.0 on 2022-01-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0003_polotician_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='polotician_detail',
        ),
    ]
