# Generated by Django 4.0 on 2022-01-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0004_delete_polotician_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='button_text',
            new_name='button_like',
        ),
    ]
