# Generated by Django 4.0 on 2022-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0005_rename_button_text_detail_button_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('button_like', models.CharField(max_length=255)),
                ('button_dislike', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/Polititcian_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
