# Generated by Django 4.0 on 2022-01-02 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratingapp', '0006_politiciandetail_delete_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politiciandetail',
            name='button_like',
        ),
        migrations.AddField(
            model_name='politiciandetail',
            name='button_like',
            field=models.ManyToManyField(related_name='politician', to=settings.AUTH_USER_MODEL),
        ),
    ]
