# Generated by Django 4.0 on 2022-01-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0007_remove_politiciandetail_button_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politiciandetail',
            name='button_dislike',
        ),
        migrations.RemoveField(
            model_name='politiciandetail',
            name='created_date',
        ),
    ]
