# Generated by Django 4.0 on 2022-01-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0008_remove_politiciandetail_button_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciandetail',
            name='button_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='politiciandetail',
            name='button_like',
        ),
        migrations.AddField(
            model_name='politiciandetail',
            name='button_like',
            field=models.IntegerField(default=0),
        ),
    ]
