# Generated by Django 4.0 on 2022-01-03 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratingapp', '0009_politiciandetail_button_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politiciandetail',
            name='button_dislike',
        ),
        migrations.RemoveField(
            model_name='politiciandetail',
            name='button_like',
        ),
        migrations.AddField(
            model_name='politiciandetail',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
