# Generated by Django 4.0 on 2022-01-03 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratingapp', '0012_alter_politiciandetail_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiciandetail',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
