# Generated by Django 4.0 on 2022-01-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0013_alter_politiciandetail_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politiciandetail',
            name='like_count',
        ),
    ]
