# Generated by Django 4.0.1 on 2022-01-05 18:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0014_remove_politiciandetail_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politiciandetail',
            name='likes',
        ),
        migrations.AddField(
            model_name='politiciandetail',
            name='likes',
            field=models.JSONField(blank=True, default=None, verbose_name=django.contrib.auth.models.User),
        ),
    ]
